-- Crear Frontend Comentarios
-- 1. Checar la version de ng = 12.X.X 
-- 2. Instalar Bootstrap 5.0.2
-- 3. Crear componentes, interfaces y servicios (conectarnos con un Backend, reutilizar código, etc)
-- 4. Modificar Navbar
-- totalidad del frontend
-- 5. Modificar ListComentario
-- 6. Routing
-- 7. Agregar comentario
-- 8. Agregar comentario: Bind campos 
-- 9. Agregar commentario: Validaciones
-- 10. Ver comentario
-- Terminado nuestro Frontend 01/02/2024 
-- Terminado nuestro Backend 07/02/2024
-- 11. Conectarnos del frontend al Backend
-- 12. Listar y eliminar comentarios
-- 13. Ver comentario (9/02/2024)
-- 14. Guardar comentario (9/02/2024)
-- 15. Actualizar comentario (10/02/2024)